# permissions for end users to view aviloadbalancerservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aviloadbalancerservice-viewer-role
rules:
- apiGroups:
  - network.lighteness.com
  resources:
  - aviloadbalancerservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.lighteness.com
  resources:
  - aviloadbalancerservices/status
  verbs:
  - get
